name: ArgoCD Kustomize Validation
on:
  push:
    branches:
      - main
jobs:
  argocd-kustomize-validation:
    name: "ArgoCD Kustomize Validation"
    runs-on: ubuntu-latest
    steps:
      - name: "[SETUP] Checkout"
        uses: actions/checkout@v3
      - name: "[TEST] Run"
        uses: ./
        with:
          chartmuseum-url: https://chartmuseum.util.riiid.cloud
          chartmuseum-username: riiid
          chartmuseum-password: 1234
